Schedule ndt7 and bbr-terminated tests
m-lab/packet-test pull request #14
Opened 2024-06-05 17:20 UTC by cristinaleonr

This PR adds ndt7 and bbr-terminated tests to the batch scheduling script. 

There are also a couple changes to the client/server code to make that possible.

2024-06-05 17:40 UTC, nkinkade requested changes
Was it intentional that the pair1 test went away from the batch script?

Also, with the script as it is, it is going to run 32 ndt7 tests every 15 minutes. Granted, some of them will exit earlier than normal ndt7, but it seems like way too much for almost anyone to want to run this on their local network. It's not really a concern with the packet dispersion tests, because my understanding is they are ultra lightweight. 

It seems like the script should be revised to only run every few hours, and to only run ndt7 tests against a single sandbox machine. Maybe something like the following and increasing the sleep to 3h?

```
servers=(
  "mlab1-lga0t"
  "mlab2-lga0t"
  "mlab3-lga0t"
  "mlab4-lga0t"
  "mlab1-lga1t"
  "mlab2-lga1t"
  "mlab3-lga1t"
  "mlab4-lga1t"
)

server=${servers[ $RANDOM % ${#servers[@]} ]}
```

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/packet-test/14#-:-NzdQzep-rrxCYb760kK:bwervas)* status: 1 change requests, 0 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2024-06-07 01:08 UTC, cristinaleonr reviewed
Yes, `train1` seems to more closely approximate `ndt7` results than `pair1`, so we don't need to run both tests.

I changed the script to target 1 sandbox server. The array example did not compile.

I increased the sleep to 3h.

> *[Reviewable](https://reviewable.io/reviews/m-lab/packet-test/14#-:-NzkE1u26IhtBIZY-kjS:bmc7i64)* status: 1 change requests, 0 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2024-06-07 01:55 UTC, nkinkade approved these changes
Thanks, LGTM. 

Probably the reason my suggestion didn't work is because the magic suggestion in batch.sh is `#!/bin/sh`, and probably almost everything in my suggestion is pure bash-isms. Targeting a static server is probably fine, but if you wanted to somewhat randomize the server, then changing to bash would help, with my method just one of many possible ways to try to randomize the server.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/packet-test/14#-:-NzkOEKc9pd9n4chVU26:b-d8hg7t)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2024-06-07 16:05 UTC, cristinaleonr reviewed
Thanks! I will leave it this way for now. Targeting one sandbox server every 3 hours should not be disruptive.

> *[Reviewable](https://reviewable.io/reviews/m-lab/packet-test/14#-:-NznRVrA1wNwMTeDWZul:byn3s8a)* status: <span>:shipit:</span> complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2024-06-07 16:05 UTC, merged